In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
x=df[["area"]]
x

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [8]:
y=df[["price"]]
y

price
0  550000
1  565000
2  610000
3  680000
4  725000

In [12]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [16]:
model.predict([[3500]])

C:\Users\PRIYA\deep_learn\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[655873.28767123]])

In [32]:
import pandas as pd
import numpy as np 
from sklearn import linear_model
import math 


In [33]:
df=pd.read_csv("homeprices-Copy1.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [34]:
bedroom=math.floor(df.bedrooms.median())
bedroom

4

In [35]:
df.bedrooms=df.bedrooms.fillna(bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [39]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [40]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [41]:
model.intercept_

221323.00186540443

In [43]:
model.predict([[3600,5,30]])

C:\Users\PRIYA\deep_learn\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([644740.6559878])

In [68]:
import pandas as pd
import numpy as np 
from sklearn import linear_model
import math 

In [69]:
df=pd.read_csv("Insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
x_train,x_test,y_train,y_test =train_test_split(df[['age']],df.bought_insurance,test_size=0.1)
x_test

age
19   18
23   45
26   23

In [72]:
from sklearn.linear_model import LogisticRegression


In [73]:
model = LogisticRegression()

In [74]:
model.fit(x_train,y_train)

LogisticRegression()

In [75]:
model.predict(x_test)

array([0, 1, 0], dtype=int64)

In [76]:
model.score(x_test,y_test)

1.0

In [80]:
model.predict([[60]])

C:\Users\PRIYA\deep_learn\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)